attach(coredata)
coredata = read.table("ASW.dat", header = TRUE)
attach(coredata)
Calcite
hist(TOC)
plot(ecdf(TOC), TOC)
norm_TOC = rnorm(TOC, mean(TOC), sd(TOC))
lines(ecdf(norm_TOC))
norm_TOC
qqnorm(TOC)
qqline(TOC)
hist(Corrected.Por)
norm_Por = rnorm(Corrected.Por, mean(Corrected.Por), sd(Corrected.Por))
norm_Por
plot(ecdf(Corrected.Por), Corrected.Por)
lines(ecdf(norm_Por))
qqnorm(Corrected.Por)
qqline(Corrected.Por)
hist(coredata)
plot(ecdf(coredata), coredata)
plot(coredata)
qqplot(coredata)
coredata = read.table("ASW.dat", header = TRUE)
attach(coredata)
hist(Quartz)
plot(ecdf(Quartz), Quartz)
norm_Quartz = rnorm(Quartz, mean(Quartz), sd(Quartz))
lines(ecdf(norm_Quartz))
qqnorm(Quartz)
qqline(Quartz)
hist(Calcite)
plot(ecdf(Calcite), Calcite)
norm_Calcite = rnorm(Calcite, mean(Calcite), sd(Calcite))
lines(ecdf(norm_Calcite))
qqnorm(Calcite)
qqline(Calcite)
hist(Dolomite)
plot(ecdf(Dolomite), Dolomite)
norm_Dolomite = rnorm(Dolomite, mean(Dolomite), sd(Dolomite))
lines(ecdf(norm_Dolomite))
qqnorm(Dolomite)
qqline(Dolomite)
hist(Illite)
plot(ecdf(Illite), Illite)
norm_Illite = rnorm(Illite, mean(Illite), sd(Illite))
lines(ecdf(norm_Illite))
qqnorm(Illite)
qqline(Illite)
lin_Por_TOC = lm(Corrected.Por ~ TOC)
lin_Por_TOC
plot(TOC, Corrected.Por)
abline(lin_Por_TOC)
abline(3.323, 0.254)
plot(TOC, residuals(lin_Por_TOC))
lin_Por_Qtz = lm(Corrected.Por ~ Quartz)
lin_Por_Qtz
plot(Quartz, Corrected.Por)
abline(lin_Por_Qtz)
plot(Quartz, residuals(lin_Por_Qtz))
lin_Por_Cal = lm(Corrected.Por ~ Calcite)
lin_Por_Cal
plot(Calcite, Corrected.Por)
abline(lin_Por_Cal)
plot(Calcite, residuals(lin_Por_Cal))
lin_TOC_Por = lm(TOC ~ Corrected.Por)
lin_TOC_Por
plot(Corrected.Por, TOC)
abline(lin_TOC_Por)
plot(Corrected.Por, residuals(lin_TOC_Por))
lin_TOC_Qtz = lm(TOC ~ Quartz)
lin_TOC_Qtz
plot(Quartz, TOC)
abline(lin_TOC_Qtz)
plot(Quartz, residuals(lin_TOC_Qtz))
lin_TOC_Cal = lm(TOC ~ Calcite)
lin_TOC_Cal
plot(Calcite, TOC)
abline(lin_TOC_Cal)
plot(Calcite, residuals(lin_TOC_Cal))
lin_Qtz_Por = lm(Quartz ~ Corrected.Por)
lin_Qtz_Por
plot(Corrected.Por, Quartz)
abline(lin_Qtz_Por)
plot(Corrected.Por, residuals(lin_Qtz_Por))
lin_Qtz_TOC = lm(Quartz ~ TOC)
lin_Qtz_TOC
plot(TOC, Quartz)
abline(lin_Qtz_TOC)
plot(TOC, residuals(lin_Qtz_TOC))
lin_Qtz_Cal = lm(Quartz ~ Calcite)
lin_Qtz_Cal
plot(Calcite, Quartz)
abline(lin_Qtz_Cal)
plot(Calcite, residuals(lin_Qtz_Cal))
lin_Cal_Por = lm(Calcite ~ Corrected.Por)
lin_Cal_Por
plot(Corrected.Por, Calcite)
abline(lin_Cal_Por)
plot(Corrected.Por, residuals(lin_Cal_Por))
lin_Cal_TOC = lm(Calcite ~ TOC)
lin_Cal_TOC
plot(TOC, Calcite)
abline(lin_Cal_TOC)
plot(TOC, residuals(lin_Cal_TOC))
lin_Cal_Qtz = lm(Calcite ~ Quartz)
lin_Cal_Qtz
plot(Quartz, Calcite)
abline(lin_Cal_Qtz)
plot(Quartz, residuals((lin_Cal_Qtz)))
covraiance = cov(coredata)
rm(covraiance)
correlation = cor(coredata)
correlation
covariance = cov(coredata)
covariance
rm(lin_Por)
lin_Por = lm(Corrected.Por ~ TOC+Quartz+Calcite)
lin_Por
coef(lin_Por)
plot(lin_Por)
print(lin_Por)
